In [ ]:
# Boolean / Logical
# two value True or False


In [ ]:
# operators in python
# equal ==
# not equal != or <> 
# And or OR 
# Greater than or Equal To =>
# Less than or Equal to <=

In [ ]:
x = 10
y = 20
z = x>y
print (z) 

z= y>x
print (z)

z = x==y
print(z)
type(z)
z= !(x==y)
print(z)

In [15]:
result= not(5>1)
print(result)
result1 = (1<5)
print(result1)
print (result and result1)
print(result or result1)

False
True
False
True


In [16]:
# while loop

year = 1
balance = 50
rate = 0.50

while (year<=10):
    balance = balance + balance * rate
    print("Year :" + str(year) + " :  " + str((balance)))
    year = year + 1
    
print ("Sucessful balance calculation for ten years after 10 looping")

Year :1 :  75.0
Year :2 :  112.5
Year :3 :  168.75
Year :4 :  253.125
Year :5 :  379.6875
Year :6 :  569.53125
Year :7 :  854.296875
Year :8 :  1281.4453125
Year :9 :  1922.16796875
Year :10 :  2883.251953125
Sucessful balance calculation for ten years after 10 looping


In [18]:
balance = 5000
rate = 1.02
year = 1
while year <=10:
	balance = balance * rate
	print ("Year: " + str(year) + ": " + str(round(balance)))
	year = year + 1

Year: 1: 5100
Year: 2: 5202
Year: 3: 5306
Year: 4: 5412
Year: 5: 5520
Year: 6: 5631
Year: 7: 5743
Year: 8: 5858
Year: 9: 5975
Year: 10: 6095


In [19]:
# For loop
mylist = [10, 20, 30, 40]

for i in mylist:
    print ("List of elements", i)

List of elements 10
List of elements 20
List of elements 30
List of elements 40


In [ ]:
# -2----- -1----- 0------1+-------2+
import numpy as np
from numpy.random import randn
randn()

In [ ]:
x=randn()
if x>1:
    print("It is greater than 1 or less than 2 number:", x)
    if x>0:
        print("It is greater than 0 or less than 1:", x)
else:
    print("It is less than 0 or greater than -1 number:", x)
    if x<-1:
        print("It is greater than -2 or less than -1:", x)

In [ ]:
x=randn()
answer= None
if x>1:
    answer = ("greater than 1:", x)
else:
    answer = ("It is less than 1:", x) 
print(answer)

In [ ]:
# Nested statement: 
x=randn()
answer= None
if x>1:
    answer = ("greater than 1:", x)
else:
    if x>=-1:
        answer = ("It is between -1 & 1:", x)
    else:
        answer = ("It is less than -1:", x)
print(answer)

In [ ]:
# What is a list
# not like vector
# it can hold of mix of data type: string,logical, integer elements)
# It is like array of one dimension
# list can hold another list inside of list

In [74]:
#Update element
help(len)
help(mylist)


Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.

Help on list object:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=valu

In [20]:
MyList = ['apple', 'Orange', 'Pears', 120,  40]
L3= [90, True, False, 'How are you', 50]

List1 = [5, 'Kabir', MyList, L3]

print(List1)

[5, 'Kabir', ['apple', 'Orange', 'Pears', 120, 40], [90, True, False, 'How are you', 50]]


In [77]:
# Range is in Python 3, but Python 2.7 used to be xrange
range(15)
print(list(range(15)))


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


In [88]:
# List can be started with any starting numbers like 100
# specify what number to start and end and also sequence number or step

x= list(range(1,8))
print(x)
x1 = list(range(100, 110))
print(x1)
x2 = list(range(100, 110,2))
print(x2)
x3 = list(range(100, 200,10))
print(x3)

[1, 2, 3, 4, 5, 6, 7]
[100, 101, 102, 103, 104, 105, 106, 107, 108, 109]
[100, 102, 104, 106, 108]
[100, 110, 120, 130, 140, 150, 160, 170, 180, 190]


In [91]:
# Using [] bracket to extract elements or updates elements in the list
w=['a', 'b', 'c', 'd', 'e', 'f', 'g']
print(w[0])
print(w[-1])

a
g


In [92]:
# updating element though indexing + or -
# overwriting the existing value
w[1]='x'
w[-1] = 20
print(w)

['a', 'x', 'c', 'd', 'e', 'f', 20]


In [ ]:
# 0  1  2  3  4 Starts with 0, left to right, different behavior compare to R programming
#-5 -4  -3 -2 -1 right to left

In [29]:
# Slicing, how to extract Element from List by Slicing
# Start:End : Step
Letters =['A', 'C', 'D', 'E', 'F', 'G', 'H', 'I','J','K']
print(Letters)

['A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K']


In [93]:
# Indexing from 1 to 5, but 5 is not included
Letters[1:5]

['C', 'D', 'E', 'F']

In [31]:
# Every 2nd Step extracting Element
Letters[2:9:2]

['D', 'F', 'H', 'J']

In [32]:
# Extracting right to left Element which start -1 and Left to right start with 0 index
Letters[-1:]

['K']

In [94]:
# Same result but two different ways of idexing
print(Letters[-8:7])
print(Letters[-8:-3])

['D', 'E', 'F', 'G', 'H']
['D', 'E', 'F', 'G', 'H']


In [34]:
Letters[-10:-2]

['A', 'C', 'D', 'E', 'F', 'G', 'H', 'I']

In [99]:
print(Letters)
# Step sequence 3
print(Letters[::3])
print(Letters[1:-3:3])

['A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K']
['A', 'E', 'H', 'K']
['C', 'F']


In [37]:
# Reverse Sequence
Letters[::-1]

['K', 'J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'A']

In [ ]:
t = (123, 20, 300, 90)

In [97]:
Letters[::-3]

['K', 'H', 'E', 'A']

In [104]:
# since -2, right to left, that's why six greater than 1 
print(Letters[:])
print(Letters[6:1:-2])

['A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K']
['H', 'F', 'D']


In [ ]:
Letters[6:1:-2]

In [ ]:
#Tuples:
# immutable list
# you can access to each element, can't update elements of tuple
# object should be able to getting updated

In [105]:
t = (30, 50, 90, 130)
t

(30, 50, 90, 130)

In [107]:
# You can extract element, but you can't update it
t[2]

90

In [108]:
# TypeError: 'tuple' object does not support item assignment
t[2] = 100

TypeError: 'tuple' object does not support item assignment

In [72]:
# built in Functions or method that are useful using Oblect. then Tab
m = [20, 10, 40, 60, 110, 400, 900, 4]
print(m)

[20, 10, 40, 60, 110, 400, 900, 4]


In [109]:
print(max(m))
print(min(m))
print(len(m))

900
4
8


In [111]:
import scrapy

In [117]:
from scrapy.crawler import CrawlerProcess
CrawlerProcess.join

SyntaxError: invalid syntax (<ipython-input-117-e2b035f34d8a>, line 2)

In [118]:
# Arrays in Python, biult in Array Array
# Why Array is important when List can hold multiple data types
# List has built function but Array has more fuctions than List
# Array can't have different data types, Array needs same data type, otherwise it will alter them

import numpy as np

In [149]:
l = [140, 40, 60, 90, 200, -10, 20, 5]

In [123]:
# type a and then tab to bring list of function and select mean
np.mean(l)

86.66666666666667

In [150]:
# NOW passing list into array, one dimensional array
a=np.array(l)
print(a)

[140  40  60  90 200 -10  20   5]


In [ ]:
# Array can't have different data type, that why integer or float have been turned into string

In [151]:
# creating array mix of float, integer and string.Let me see Array can't work with different data types.
b=np.array([200, 40.56, 'True', 'abc'])
print(b)

['200' '40.56' 'True' 'abc']


In [126]:
# Every element of Array turned to be string data type
print(b)

['200' '40.56' 'True' 'abc']


In [152]:
# List has buit in function or method on TAB
l.pop()

5

In [128]:
# remove the last element from list by using function pop
l

[140, 40, 60, 90, 200]

In [172]:
print(a)

[-10   5  20  40 500  90 140 200]


In [168]:
# Build function Tab for Array as well
# list of elements in Array 
a.sort()
print(a)
a.mean()

[-10   5  20  40  80  90 140 200]


70.625

In [159]:
b=a[1:5]

In [171]:
# Array b derieved from a which contain 10, 40, 60, 90, 140, 200
b

array([  5,  20,  40, 500])

In [170]:
# Array updated to 80 for indexing 3: Updating to 500 array b that has also updated to Array a
b[3:]=[500]
print(b)

[  5  20  40 500]


In [174]:
b

array([  5,  20,  40, 500])

In [177]:
# Now Array a that has been updated to 500 in indexing 3:. So it can't be copied
# creating a new array by slicing, it is not new but original array also gets updated
# 
print(a)

[-10   5  20  40 500  90 140 200]


In [180]:
# copying Array a to c
c= a.copy()
print(a)
print(c)

[-10   5  20  40 500  90 140 200]
[-10   5  20  40 500  90 140 200]


In [182]:
c[7:] = [1000]
# after copying to c and updating c inex 7th, that did not get updated array a. that is difference copying
print(a)
print(c)

[-10   5  20  40 500  90 140 200]
[ -10    5   20   40  500   90  140 1000]


In [144]:
a=6
b=3
def func1(a, b):
    return a / b


print(a / b)

x=10
def func2(x):
    a = x
    b = x - 1
    return (x, x-1)
print(a, b)
print(x, x-1)

2.0
6 3
10 9


In [145]:
l = ['aaa', 'bbb', 'ccc']

In [10]:
s = ''.join(l)
print(s)

aaabbbccc


In [188]:

def func1(a, b):
    return a / b
print(func1(3,6))

def func2(x):
    a = x
    b = x - 5
    return(a, b)
print (func2(20))

0.5
(20, 15)


In [189]:
L5=[2, 5, 10, 20, 400, 30]

len(L5)

4

In [200]:
# Keep appending
L5.append(100)
print(L5)

[2, 5, 10, 20, 100, 100, 100, 100, 100, 100]


In [205]:
# Keep de-appending
L5.remove(100)
print(L5)

[2, 5, 10, 20, 100, 100, 100, 100]


In [207]:
# which index should be inserted into like 0 to 8. It can also over-write
L5.insert(0,1000)
print(L5)

[1000, 1000, 2, 5, 10, 20, 100, 100, 100, 100]


In [209]:
L5.clear
print(L5)

[1000, 1000, 2, 5, 10, 20, 100, 100, 100, 100]


In [ ]:
x=6.0
print(2*x + 3)

In [ ]:
x=5.0
print('{X} has type {T}'.format(X=x, T=type(x)))
print(f'{x} has type {type(x)}')

In [ ]:
a=5
b=3
c= a/b
print(c)

In [211]:
L =[8, 7, 2, 5, 1]
L

[8, 7, 2, 5, 1]

In [212]:
# You have to use print to receive the result
print(min(L))
print(max(L))

1
8


In [213]:
L=[8, 7, 2, 5, 1]
def remove_all(L, x):
    assert type(L) is list and x is not None
    Lcopy = []
    Lcopy = L + []
    xcount= Lcopy.count(x)
    print(xcount)
    print(x)
    print(Lcopy)
    return xcount

In [55]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array
print(x1)
print(x2)
print(x3)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [57]:
import requests
from bs4 import BeautifulSoup
page = requests.get('https://www.ibm.com')
print(page)

<Response [200]>


In [214]:
soup=BeautifulSoup(page, "html.parser")
artists = soup.find_all('a')
print(artists)

TypeError: object of type 'Response' has no len()

In [59]:
L=[2, 4, 6, 8, 10]
len(L)

5

In [218]:
L.insert(0, 20)

In [219]:
L[5]= 100
print(L)

[20, 8, 7, 2, 5, 100, 20]
